### ISSUE TITLE
[FEAT] Добавь хоткей в категорию

### ISSUE THREAD

**Issue by TaggedDev** [IOExcept10n/KeyBindingsEditor#2]
В контекстном меню создания категории добавь хоткей Enter, чтобы можно было создать новый экшен

**Comment by TaggedDev** [comment]
Можно в общем-то и навигацию по стрелкам сделать

**Comment by TaggedDev** [comment]
И переключение между Action name и action description на TAB и Shift TAB

**Comment by IOExcept10n** [comment]
> И переключение между Action name и action description на TAB и Shift TAB

Такое переключение у меня и так работает

**Comment by IOExcept10n** [comment]
Частично реализовано в v1.2
Навигация по стрелкам не будет реализована, так как полоса прокрутки перехватывает обработку на стрелки
