### ISSUE TITLE
[BUG] При удалении Action с уже установленным биндом происходит странный ребинд

### ISSUE THREAD

**Issue by TaggedDev** [IOExcept10n/KeyBindingsEditor#7]
Ожидается, что при удалении Action будет удалены все бинды на этот экшен. Однако у меня получилось, что бинд перебиндился на другой экшен.

1. Созданы 3 бинда: Main, secondary, third
2. Кнопке F задан бинд secondary
3. Secondary action удаляется (ожидается, что кнопка F будет очищена)
4. Выходит, что кнопка F забиндилась на main action

**Comment by IOExcept10n** [comment]
Исправил
